# Generated by Django 4.0.2 on 2022-02-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=600)),
                ('text', models.TextField(max_length=600)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('tags', models.TextField(max_length=23)),
                ('image', models.ImageField(upload_to='yazilar/%Y/%m/%d/')),
            ],
        ),
    ]
