# Generated by Django 4.0.2 on 2022-02-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_yazilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilar',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
